

services:
  web:
    build: .
    container_name: handyman-web
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_DB: handyman_db
      POSTGRES_USER: handyman_user
      POSTGRES_PASSWORD: offerland_django123
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    env_file:
      - .env
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:17.2
    container_name: postgres_db3
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U handyman_user -d handyman_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: handyman_db
      POSTGRES_USER: handyman_user
      POSTGRES_PASSWORD: offerland_django123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: